import React from "react";

const iconProps = { className: "h-4 w-4" };

export const Activity = (props: any) => <span {...props}>●</span>;
export const AlertTriangle = (props: any) => <span {...props}>⚠</span>;
export const Avatar = (props: any) => <span {...props}>👤</span>;
export const Badge = (props: any) => <span {...props}>◆</span>;
export const Button = (props: any) => <span {...props}>▢</span>;
export const Calendar = (props: any) => <span {...props}>📅</span>;
export const CalendarCheck = (props: any) => <span {...props}>✓</span>;
export const CalendarDays = (props: any) => <span {...props}>📅</span>;
export const Card = (props: any) => <span {...props}>▢</span>;
export const Check = (props: any) => <span {...props}>✓</span>;
export const CheckCircle2 = (props: any) => <span {...props}>✓</span>;
export const ChevronDown = (props: any) => <span {...props}>▼</span>;
export const Clock = (props: any) => <span {...props}>🕐</span>;
export const Clock3 = (props: any) => <span {...props}>🕐</span>;
export const ClipboardCheck = (props: any) => <span {...props}>✓</span>;
export const Eye = (props: any) => <span {...props}>👁</span>;
export const FolderKanban = (props: any) => <span {...props}>📁</span>;
export const History = (props: any) => <span {...props}>⏱</span>;
export const ListChecks = (props: any) => <span {...props}>☑</span>;
export const Loader2 = (props: any) => <span {...props} className="animate-spin">⟳</span>;
export const Mail = (props: any) => <span {...props}>✉</span>;
export const MapPin = (props: any) => <span {...props}>📍</span>;
export const Power = (props: any) => <span {...props}>⏻</span>;
export const RotateCcw = (props: any) => <span {...props}>↻</span>;
export const Users = (props: any) => <span {...props}>👥</span>;
export const UserRoundCheck = (props: any) => <span {...props}>✓👤</span>;
export const Zap = (props: any) => <span {...props}>⚡</span>;
